name: Checking dig-Eds-cat URLs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  urlcheck:
    name: Check URLs
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python Packages
        run: pip install -r requirements.txt

      - name: Run checker
        run: python scripts/url_checker.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update URL check results
          title: Update URL Health Check Results
          body: |
            Automated URL health check results from GitHub Actions
            - Updated `result.csv` with latest URL check results
          branch: url-health-check
          delete-branch: true
          base: main