name: Checking dig-Eds-cat URLs

on:
  workflow_dispatch:

jobs:
  urlcheck:
    name: dump baserow
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Setu up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: run checker
        run: python scripts/url_checker.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Checked dig-Eds-cat URLs